# Generated by Django 4.1.6 on 2023-03-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("cpassword", models.CharField(max_length=200)),
                ("phonenumber", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=400)),
            ],
        ),
    ]
